improvement: added messaging to install/uninstall

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,11 +2,22 @@
 this_dir=$(dirname $(realpath ${BASH_SOURCE:-$0}))
 plugin_dir=/usr/share/zsh/plugins/fzf-help
 
-echo "Deleting old $plugin_dir"
-rm -r $plugin_dir 2>/dev/null || echo "No old installation found."
+if [[ -d $plugin_dir ]]; then
+    echo "Found old installation at $plugin_dir"
+    echo "Deleting old installation..."
+    sudo rm -rf $plugin_dir || {
+        echo 'installation aborted'
+        exit 0
+    }
+fi
 
 echo "Copying fzf-help to $plugin_dir"
-mkdir $plugin_dir
-cp $this_dir/src/* $plugin_dir
-
+sudo mkdir $plugin_dir || {
+    echo 'installation aborted'
+    exit 0
+}
+sudo cp $this_dir/src/* $plugin_dir || {
+    echo 'installation aborted'
+    exit 0
+}
 echo 'Installation complete.'
diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -2,7 +2,15 @@
 this_dir=$(dirname $(realpath ${BASH_SOURCE:-$0}))
 plugin_dir=/usr/share/zsh/plugins/fzf-help
 
-echo "Deleting old installation at: $plugin_dir"
-rm -r $plugin_dir 2>/dev/null || echo "No old installation found."
+if [[ -d $plugin_dir ]]; then
+    echo "Deleting old installation at: $plugin_dir"
+    sudo rm -rf $plugin_dir || {
+        echo 'Failed to delete old installation.'
+        exit 1
+    }
+else
+    echo 'fzf-help is not installed.'
+    exit 0
+fi
 
 echo 'Uninstall complete.'
